name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: python -m pip install -e .[release]
      - name: Build release
        run: python -m build --sdist --wheel
      - name: Generate release notes
        run: |
          python scripts/release_notes.py ${{ github.ref_name }} \
            >${{ github.workspace }}-RELEASE.md
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-RELEASE.md
          files: dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
